version: "3"

networks:
  luby-cash:
    external: true

services:
  app:
    container_name: luby-cash-api-adonis
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    image: luby-cash-api-adonis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - luby-cash
    depends_on:
      - db
    ports:
      - '3333:3333'

  db:
    container_name: db-luby-cash
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=126453
      - MYSQL_DATABASE=db_luby_cash
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - luby-cash
    command: mysqld --innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password
    volumes:
      - /db/var/lib/mysql
